TakeHomeChallengeTask/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TakeHomeChallengeTask/force-app/main/default/objects/Booking__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

TakeHomeChallengeTask/force-app/main/default/classes/CreateEventOnContactClassTest.cls
@isTest(seeAllData=false)
public class CreateEventOnContactClassTest {

    @testSetup static void setup(){
        //create account
        Account account = new Account();
        account.Name = 'Test account';
        insert account;
        //create contact
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.LastName = 'Test contact';
        insert contact;
        
        Date todayDate = date.today();
        Date futureDate = todayDate.addDays(7);
        
        //create event
         Event event = new Event();
         event.WhoId = contact.Id;
         event.OwnerId = UserInfo.getUserId();
         event.Subject = 'Test event creation'; 
         event.ActivityDate = futureDate;
         event.ActivityDateTime = futureDate;
         event.DurationInMinutes = 30;
         insert event;
       
    }
    
    @isTest static void createEventOnContactTest() {
        Contact contact = [select id from contact where LastName='Test contact'];
        Booking__c booking = new Booking__c();
        booking.ContactId__c = contact.Id;
        try{
            insert booking;
        }catch(Exception e){
            
        }
        
        
        //system.assertEquals(data.numberDaysDueTask, 7, 'Expected output is same as actual output');
        //system.assertEquals(data.numberDaysDueEvent, 7, 'Expected output is same as actual output');
    }
}